# Generated by Django 5.0.6 on 2024-06-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('Mobile_No', models.IntegerField(max_length=10)),
                ('Fee', models.IntegerField(max_length=5)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
