# Generated by Django 5.0.6 on 2024-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Mobile_No',
            field=models.IntegerField(),
        ),
    ]
